#!/bin/sh

#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency

nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/1MB_dot.out python3 __init__.py 0 512 512 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/2MB_dot.out python3 __init__.py 0 512 1024 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/4MB_dot.out python3 __init__.py 0 512 2048 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/8MB_dot.out python3 __init__.py 0 512 4096 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/16MB_dot.out python3 __init__.py 0 512 8192 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/32MB_dot.out python3 __init__.py 0 512 16384 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/64MB_dot.out python3 __init__.py 0 512 32768 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/128MB_dot.out python3 __init__.py 0 512 65536 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/256MB_dot.out python3 __init__.py 0 512 131072 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/512MB_dot.out python3 __init__.py 0 512 262144 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/1GB_dot.out python3 __init__.py 0 512 524288 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/1GB_dot.out python3 __init__.py 0 512 524288 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/1.5GB_dot.out python3 __init__.py 0 512 786432 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/2GB_dot.out python3 __init__.py 0 512 1048576 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/3GB_dot.out python3 __init__.py 0 512 1572864 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/4GB_dot.out python3 __init__.py 0 512 2097152 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/8GB_dot.out python3 __init__.py 0 512 4194304 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/dot/10GB_dot.out python3 __init__.py 0 512 5242880 10 0

nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/1MB_mul.out python3 __init__.py 1 512 512 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/2MB_mul.out python3 __init__.py 1 512 1024 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/4MB_mul.out python3 __init__.py 1 512 2048 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/8MB_mul.out python3 __init__.py 1 512 4096 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/16MB_mul.out python3 __init__.py 1 512 8192 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/32MB_mul.out python3 __init__.py 1 512 16384 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/64MB_mul.out python3 __init__.py 1 512 32768 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/128MB_mul.out python3 __init__.py 1 512 65536 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/256MB_mul.out python3 __init__.py 1 512 131072 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/512MB_mul.out python3 __init__.py 1 512 262144 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/1GB_mul.out python3 __init__.py 1 512 524288 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/1GB_mul.out python3 __init__.py 1 512 524288 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/1.5GB_mul.out python3 __init__.py 1 512 786432 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/2GB_mul.out python3 __init__.py 1 512 1048576 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/3GB_mul.out python3 __init__.py 1 512 1572864 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/4GB_mul.out python3 __init__.py 1 512 2097152 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/8GB_mul.out python3 __init__.py 1 512 4194304 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/mul/10GB_mul.out python3 __init__.py 1 512 5242880 10 0

nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/1MB_add.out python3 __init__.py 2 512 512 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/2MB_add.out python3 __init__.py 2 512 1024 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/4MB_add.out python3 __init__.py 2 512 2048 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/8MB_add.out python3 __init__.py 2 512 4096 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/16MB_add.out python3 __init__.py 2 512 8192 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/32MB_add.out python3 __init__.py 2 512 16384 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/64MB_add.out python3 __init__.py 2 512 32768 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/128MB_add.out python3 __init__.py 2 512 65536 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/256MB_add.out python3 __init__.py 2 512 131072 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/512MB_add.out python3 __init__.py 2 512 262144 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/1GB_add.out python3 __init__.py 2 512 524288 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/1GB_add.out python3 __init__.py 2 512 524288 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/1.5GB_add.out python3 __init__.py 2 512 786432 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/2GB_add.out python3 __init__.py 2 512 1048576 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/3GB_add.out python3 __init__.py 2 512 1572864 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/4GB_add.out python3 __init__.py 2 512 2097152 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/8GB_add.out python3 __init__.py 2 512 4194304 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/add/10GB_add.out python3 __init__.py 2 512 5242880 10 0

nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/1MB_sig.out python3 __init__.py 3 512 512 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/2MB_sig.out python3 __init__.py 3 512 1024 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/4MB_sig.out python3 __init__.py 3 512 2048 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/8MB_sig.out python3 __init__.py 3 512 4096 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/16MB_sig.out python3 __init__.py 3 512 8192 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/32MB_sig.out python3 __init__.py 3 512 16384 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/64MB_sig.out python3 __init__.py 3 512 32768 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/128MB_sig.out python3 __init__.py 3 512 65536 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/256MB_sig.out python3 __init__.py 3 512 131072 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/512MB_sig.out python3 __init__.py 3 512 262144 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/1GB_sig.out python3 __init__.py 3 512 524288 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/1GB_dot.out python3 __init__.py 3 512 524288 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/1.5GB_dot.out python3 __init__.py 3 512 786432 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/2GB_dot.out python3 __init__.py 3 512 1048576 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/3GB_dot.out python3 __init__.py 3 512 1572864 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/4GB_dot.out python3 __init__.py 3 512 2097152 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/8GB_dot.out python3 __init__.py 3 512 4194304 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/sig/10GB_dot.out python3 __init__.py 3 512 5242880 10 0

nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/1MB_softmax.out python3 __init__.py 4 512 512 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/2MB_softmax.out python3 __init__.py 4 512 1024 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/4MB_softmax.out python3 __init__.py 4 512 2048 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/8MB_softmax.out python3 __init__.py 4 512 4096 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/16MB_softmax.out python3 __init__.py 4 512 8192 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/32MB_softmax.out python3 __init__.py 4 512 16384 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/64MB_softmax.out python3 __init__.py 4 512 32768 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/128MB_softmax.out python3 __init__.py 4 512 65536 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/256MB_softmax.out python3 __init__.py 4 512 131072 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/512MB_softmax.out python3 __init__.py 4 512 262144 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/1GB_softmax.out python3 __init__.py 4 512 524288 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/1GB_softmax.out python3 __init__.py 4 512 524288 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/1.5GB_softmax.out python3 __init__.py 4 512 786432 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/2GB_softmax.out python3 __init__.py 4 512 1048576 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/3GB_softmax.out python3 __init__.py 4 512 1572864 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/4GB_softmax.out python3 __init__.py 4 512 2097152 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/8GB_softmax.out python3 __init__.py 4 512 4194304 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/softmax/10GB_softmax.out python3 __init__.py 4 512 5242880 10 0

nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/1MB_scalar.out python3 __init__.py 5 512 512 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/2MB_scalar.out python3 __init__.py 5 512 1024 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/4MB_scalar.out python3 __init__.py 5 512 2048 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/8MB_scalar.out python3 __init__.py 5 512 4096 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/16MB_scalar.out python3 __init__.py 5 512 8192 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/32MB_scalar.out python3 __init__.py 5 512 16384 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/64MB_scalar.out python3 __init__.py 5 512 32768 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/128MB_scalar.out python3 __init__.py 5 512 65536 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/256MB_scalar.out python3 __init__.py 5 512 131072 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/512MB_scalar.out python3 __init__.py 5 512 262144 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/1GB_scalar.out python3 __init__.py 5 512 524288 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/1.5GB_scalar.out python3 __init__.py 5 512 786432 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/2GB_scalar.out python3 __init__.py 5 512 1048576 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/3GB_scalar.out python3 __init__.py 5 512 1572864 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/4GB_scalar.out python3 __init__.py 5 512 2097152 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/8GB_scalar.out python3 __init__.py 5 512 4194304 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/scalar/10GB_scalar.out python3 __init__.py 5 512 5242880 10 0

nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/1MB_tanh.out python3 __init__.py 6 512 512 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/2MB_tanh.out python3 __init__.py 6 512 1024 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/4MB_tanh.out python3 __init__.py 6 512 2048 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/8MB_tanh.out python3 __init__.py 6 512 4096 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/16MB_tanh.out python3 __init__.py 6 512 8192 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/32MB_tanh.out python3 __init__.py 6 512 16384 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/64MB_tanh.out python3 __init__.py 6 512 32768 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/128MB_tanh.out python3 __init__.py 6 512 65536 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/256MB_tanh.out python3 __init__.py 6 512 131072 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/512MB_tanh.out python3 __init__.py 6 512 262144 10 0
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/1GB_tanh.out python3 __init__.py 6 512 524288 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/1.5GB_tanh.out python3 __init__.py 6 512 786432 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/2GB_tanh.out python3 __init__.py 6 512 1048576 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/3GB_tanh.out python3 __init__.py 6 512 1572864 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/4GB_tanh.out python3 __init__.py 6 512 2097152 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/8GB_tanh.out python3 __init__.py 6 512 4194304 10 0
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop/tanh/10GB_tanh.out python3 __init__.py 6 512 5242880 10 0

#shared
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/1MB_dot.out python3 __init__.py 0 512 512 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/2MB_dot.out python3 __init__.py 0 512 1024 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/4MB_dot.out python3 __init__.py 0 512 2048 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/8MB_dot.out python3 __init__.py 0 512 4096 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/16MB_dot.out python3 __init__.py 0 512 8192 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/32MB_dot.out python3 __init__.py 0 512 16384 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/64MB_dot.out python3 __init__.py 0 512 32768 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/128MB_dot.out python3 __init__.py 0 512 65536 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/256MB_dot.out python3 __init__.py 0 512 131072 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/512MB_dot.out python3 __init__.py 0 512 262144 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/1GB_dot.out python3 __init__.py 0 512 524288 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/1GB_dot.out python3 __init__.py 0 512 524288 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/1.5GB_dot.out python3 __init__.py 0 512 786432 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/2GB_dot.out python3 __init__.py 0 512 1048576 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/3GB_dot.out python3 __init__.py 0 512 1572864 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/4GB_dot.out python3 __init__.py 0 512 2097152 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/8GB_dot.out python3 __init__.py 0 512 4194304 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/dot/10GB_dot.out python3 __init__.py 0 512 5242880 10 1

nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/1MB_mul.out python3 __init__.py 1 512 512 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/2MB_mul.out python3 __init__.py 1 512 1024 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/4MB_mul.out python3 __init__.py 1 512 2048 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/8MB_mul.out python3 __init__.py 1 512 4096 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/16MB_mul.out python3 __init__.py 1 512 8192 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/32MB_mul.out python3 __init__.py 1 512 16384 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/64MB_mul.out python3 __init__.py 1 512 32768 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/128MB_mul.out python3 __init__.py 1 512 65536 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/256MB_mul.out python3 __init__.py 1 512 131072 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/512MB_mul.out python3 __init__.py 1 512 262144 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/1GB_mul.out python3 __init__.py 1 512 524288 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/1.5GB_mul.out python3 __init__.py 1 512 786432 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/2GB_mul.out python3 __init__.py 1 512 1048576 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/3GB_mul.out python3 __init__.py 1 512 1572864 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/4GB_mul.out python3 __init__.py 1 512 2097152 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/8GB_mul.out python3 __init__.py 1 512 4194304 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/mul/10GB_mul.out python3 __init__.py 1 512 5242880 10 1

nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/1MB_add.out python3 __init__.py 2 512 512 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/2MB_add.out python3 __init__.py 2 512 1024 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/4MB_add.out python3 __init__.py 2 512 2048 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/8MB_add.out python3 __init__.py 2 512 4096 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/16MB_add.out python3 __init__.py 2 512 8192 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/32MB_add.out python3 __init__.py 2 512 16384 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/64MB_add.out python3 __init__.py 2 512 32768 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/128MB_add.out python3 __init__.py 2 512 65536 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/256MB_add.out python3 __init__.py 2 512 131072 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/512MB_add.out python3 __init__.py 2 512 262144 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/1GB_add.out python3 __init__.py 2 512 524288 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/1.5GB_add.out python3 __init__.py 2 512 786432 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/2GB_add.out python3 __init__.py 2 512 1048576 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/3GB_add.out python3 __init__.py 2 512 1572864 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/4GB_add.out python3 __init__.py 2 512 2097152 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/8GB_add.out python3 __init__.py 2 512 4194304 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/add/10GB_add.out python3 __init__.py 2 512 5242880 10 1

nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/1MB_sig.out python3 __init__.py 3 512 512 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/2MB_sig.out python3 __init__.py 3 512 1024 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/4MB_sig.out python3 __init__.py 3 512 2048 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/8MB_sig.out python3 __init__.py 3 512 4096 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/16MB_sig.out python3 __init__.py 3 512 8192 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/32MB_sig.out python3 __init__.py 3 512 16384 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/64MB_sig.out python3 __init__.py 3 512 32768 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/128MB_sig.out python3 __init__.py 3 512 65536 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/256MB_sig.out python3 __init__.py 3 512 131072 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/512MB_sig.out python3 __init__.py 3 512 262144 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/1GB_sig.out python3 __init__.py 3 512 524288 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/1.5GB_sig.out python3 __init__.py 3 512 786432 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/2GB_sig.out python3 __init__.py 3 512 1048576 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/3GB_sig.out python3 __init__.py 3 512 1572864 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/4GB_sig.out python3 __init__.py 3 512 2097152 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/8GB_sig.out python3 __init__.py 3 512 4194304 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/sig/10GB_sig.out python3 __init__.py 3 512 5242880 10 1

nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/1MB_softmax.out python3 __init__.py 4 512 512 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/2MB_softmax.out python3 __init__.py 4 512 1024 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/4MB_softmax.out python3 __init__.py 4 512 2048 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/8MB_softmax.out python3 __init__.py 4 512 4096 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/16MB_softmax.out python3 __init__.py 4 512 8192 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/32MB_softmax.out python3 __init__.py 4 512 16384 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/64MB_softmax.out python3 __init__.py 4 512 32768 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/128MB_softmax.out python3 __init__.py 4 512 65536 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/256MB_softmax.out python3 __init__.py 4 512 131072 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/512MB_softmax.out python3 __init__.py 4 512 262144 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/1GB_softmax.out python3 __init__.py 4 512 524288 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/1.5GB_softmax.out python3 __init__.py 4 512 786432 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/2GB_softmax.out python3 __init__.py 4 512 1048576 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/3GB_softmax.out python3 __init__.py 4 512 1572864 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/4GB_softmax.out python3 __init__.py 4 512 2097152 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/8GB_softmax.out python3 __init__.py 4 512 4194304 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/softmax/10GB_softmax.out python3 __init__.py 4 512 5242880 10 1

nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/1MB_scalar.out python3 __init__.py 5 512 512 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/2MB_scalar.out python3 __init__.py 5 512 1024 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/4MB_scalar.out python3 __init__.py 5 512 2048 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/8MB_scalar.out python3 __init__.py 5 512 4096 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/16MB_scalar.out python3 __init__.py 5 512 8192 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/32MB_scalar.out python3 __init__.py 5 512 16384 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/64MB_scalar.out python3 __init__.py 5 512 32768 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/128MB_scalar.out python3 __init__.py 5 512 65536 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/256MB_scalar.out python3 __init__.py 5 512 131072 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/512MB_scalar.out python3 __init__.py 5 512 262144 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/1GB_scalar.out python3 __init__.py 5 512 524288 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/1.5GB_scalar.out python3 __init__.py 5 512 786432 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/2GB_scalar.out python3 __init__.py 5 512 1048576 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/3GB_scalar.out python3 __init__.py 5 512 1572864 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/4GB_scalar.out python3 __init__.py 5 512 2097152 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/8GB_scalar.out python3 __init__.py 5 512 4194304 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/scalar/10GB_scalar.out python3 __init__.py 5 512 5242880 10 1

nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/1MB_tanh.out python3 __init__.py 6 512 512 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/2MB_tanh.out python3 __init__.py 6 512 1024 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/4MB_tanh.out python3 __init__.py 6 512 2048 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/8MB_tanh.out python3 __init__.py 6 512 4096 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/16MB_tanh.out python3 __init__.py 6 512 8192 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/32MB_tanh.out python3 __init__.py 6 512 16384 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/64MB_tanh.out python3 __init__.py 6 512 32768 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/128MB_tanh.out python3 __init__.py 6 512 65536 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/256MB_tanh.out python3 __init__.py 6 512 131072 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/512MB_tanh.out python3 __init__.py 6 512 262144 10 1
nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/1GB_tanh.out python3 __init__.py 6 512 524288 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/1.5GB_tanh.out python3 __init__.py 6 512 786432 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/2GB_tanh.out python3 __init__.py 6 512 1048576 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/3GB_tanh.out python3 __init__.py 6 512 1572864 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/4GB_tanh.out python3 __init__.py 6 512 2097152 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/8GB_tanh.out python3 __init__.py 6 512 4194304 10 1
#nvprof --metrics flop_count_sp,flop_sp_efficiency,flop_count_dp,flop_dp_efficiency --log-file outputFilesFlop_Shared/tanh/10GB_tanh.out python3 __init__.py 6 512 5242880 10 1
